### ISSUE TITLE
Stop using Cloudflare

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller-dev.github.io#11]
Cloudflare is absolutely privacy invasive. It can

- inject / modify JS (into the website)
- spy on you and the page's users
- track users across websites
- and the page might get blocked in some countries

Only to name some of the problems. I think it is very bad to even use it to host analytics and fonts / icons as seen on my screenshot:

![Cloudflare on OAI Website](https://user-images.githubusercontent.com/82117109/226685965-57648439-d60d-4a37-99ba-d68a5b4c11e9.png)

<br>

**Please consider** hosting the Font Awesome **CSS locally** as a static file and **stop** hosting Plausible **via Cloudflare**, there are **other options**.
I personally don't know anything about hosting Plausible, but I guess there is another way like using Vercel, etc.. (Or even going into using a small VPS?)

<br>

**Eventual alternatives**
Another interesting solution would be [Matomo](https://matomo.org), which can also - with a few settings - be turned into a very very privacy friendly solution, which does not even require a VPS or a Serverless option.
If you are interested: I personally am using [Umami](https://umami.is) (Hosted via Vercel) and Matomo.

Regarding alternatives to font-awesome here is a list:
https://alternativeto.net/software/font-awesome/?license=opensource

General European alternatives for Cloudflare:
https://european-alternatives.eu/alternative-to/cloudflare

General (European) analytics services (Just if you are interested):
https://european-alternatives.eu/category/web-analytics-services

**Comment by tsterbak** [comment]
Resolved
