### ISSUE TITLE
Suggestion for OS Recommendation

### ISSUE THREAD

**Issue by OkyDooky** [openandroidinstaller-dev/openandroidinstaller-dev.github.io#2]
I just came across this project in the XDA forums today and I am really excited and relieved, since I'm anticipating (read: dreading) having to do this process for a new phone in the semi-near future.

This is a small suggestion, but when you mention that Ubuntu is currently the best supported OS for this, maybe include a mention about live booting it from a USB. This can be great clue for new users ("oh, wait, I can do that?") and a good reminder for experienced ones ("oh, right, I can do that").
I know many use Windows and a fair number suprisingly do use mac, so that could help them get that certainty without having to install anything outside of maybe BalenaEtcher.
For Linux users, this can give them an option to maybe skip some of the headache from trying to ensure app compatibility with their distribution. Like in my case, where I use an Arch-based distro (Garuda), this popped into my head as a way to get around that issue until formal compatibility is established on the app/project end.

This could be added in just a simple parenthesis, like: (this can be booted from a USB drive, without installing the OS) and some of that text could be turned into a hyperlink.

**Comment by tsterbak** [comment]
Hey @OkyDooky,
I'm happy you found the project and thank you for the great suggestion! I just updated the website accordingly. Do you think it's reasonably clear?

Apart from that, what kind of device will you be flashing? You can find supported devices here: https://github.com/openandroidinstaller-dev/openandroidinstaller#officially-supported-devices

Let me know if you are facing any issues! I'm grateful for all the feedback I can get! :)

**Comment by OkyDooky** [comment]
Thanks! Glad it was helpful!
It looks good, except the hyperlink ends prematurely: it stops before "it" at the end of the sentence ("install it"), which interrupts the grammatical and visual flow. Other than that, it is very clear and concise, while still feeling natural.

As for device(s), I'm torn between getting a Pixel 4 XL and a Galaxy S9+ Exynos for my new phone. Those are the only two that have a powerful enough chipset to run GameCube games at full speed through Dolphin, while still being affordable (and available), not 5G, and network compatible (kinda). The indecision is on my personal feelings about getting a Google phone when I'm trying to get away from Google (just because it's powerful), contrasted with getting a foreign model because it's the only version that can have its bootloader unlocked and would have me switch carriers (I'm on Cricket, right now).

The positives are that the 4 XL is even more powerful (the only non-5G phone with the Snapdragon 855, while the others cap at 850) and has Calyx support (Graphene ended official support for that model) and full network support.
While the positives for the S9+ are that it is not Google, has expandable storage, has a powerful (though less supported) chipset, and technically can work on at least one major US network (T-Mobile).

So, while that's causing me some grief, I also have my first smartphone, a Galaxy Note 3 (T-Mobile), which I installed Lineage on a few years ago. I haven't bothered upgrading the OS version, because it required jumping through the hoops of flashing stuff on again and I really didn't want to go through that. It really got complicated the first time when I could only find the baseband modem drivers on some long-forgotten forum somewhere (I didn't bookmark it). So, that's something to consider when doing a config (apparently, the T-Mobile version is considered some obscure variant). I'll try to help, if I can. But, thankfully, I don't use it as my "phone" phone (got a new(er) one with my carrier, but it hurts my hands with the radiation and is way weaker than the ones I'm looking at), so that wouldn't be necessary for me, as long as everything else works. Either way, being able to use this tool for that in the future would be a game changer for me (especially with this older model).

I know you wantes feedback, but I guess I sound up giving you my life's story, regarding phones. Lol

(Closing because the issue is essentially resolved, but I will continue responding to any discussion!)

**Comment by tsterbak** [comment]
Discussion continues here: https://github.com/openandroidinstaller-dev/openandroidinstaller/issues/46
