### ISSUE TITLE
Using Peertube to host & embed showcase videos

### ISSUE THREAD

**Issue by MagicLike** [openandroidinstaller-dev/openandroidinstaller-dev.github.io#5]
https://github.com/openandroidinstaller-dev/openandroidinstaller/issues/71
related to #3

[Peertube](https://joinpeertube.org) is a great  video provider for such showcases and in general for update videos.

If you are on the look for a relatively small, but well managed instance with great storage options, I can recommend [Peertube.TV](https://peertube.tv).

**Comment by tsterbak** [comment]
@MagicLike I'm thinking about adding more videos and therefor moving to peertube. Sadly, Peertube.TV doesn't accept new accounts atm. Can you recommend another suited instance?

**Comment by MagicLike** [comment]
> I'm thinking about adding more videos and therefor moving to peertube. Sadly, Peertube.TV doesn't accept new accounts atm.

@tsterbak No problem, I am partly administrating the instance, I can clear you an account... (I will open registration for a short time frame, so be quick!)

**Comment by MagicLike** [comment]
They are open!

**Comment by tsterbak** [comment]
Uhh, I guess I missed it... I wasn't reading github fast enough.

**Comment by MagicLike** [comment]
np, still open!

**Comment by tsterbak** [comment]
Hm, for me it shows "Currently this instance doesn't allow for user registration" :thinking:

**Comment by MagicLike** [comment]
Ok, can you try again?

**Comment by tsterbak** [comment]
Okay perfect! :blush: I'm in :smile: Thanks a lot!
So I'll upload the demo videos immediately :)

**Comment by MagicLike** [comment]
How big are they all together?

**Comment by tsterbak** [comment]
I currently have two demo videos around 25 MB each :sweat_smile:

**Comment by MagicLike** [comment]
ok, than it is no problem... If you would have needed to upload more than 5 Gigs I could raise your daily limit ^^

**Comment by tsterbak** [comment]
Haha thank you! :) Hopefully I will never have to create that many demos :sweat_smile:

**Comment by MagicLike** [comment]
I also marked you, so that your uploads don't get auto-blacklisted... Small tip: Finish setting up your channel, it makes everything look nicer. If you need further help, just ask! :heart:

**Comment by tsterbak** [comment]
Thanks a ton for your support! That helped a lot! :relaxed:

**Comment by MagicLike** [comment]
Oh, one thing: For user privacy you should disable P2P in the embed 😉

**Comment by tsterbak** [comment]
Thank you for the hint! It is disabled now :slightly_smiling_face:

**Comment by MagicLike** [comment]
I'll close this now, if you need any further help, contact me on the fedi or via e-mail! :smiley:

**Comment by Tampa** [comment]
The currently used endpoint for the embeds has been flagged as potentially malicious so some anti-virus will block it. What exactly stands in the way of just embedding a .webm of the videos? That would be a bit less problematic than an iframe

**Comment by tsterbak** [comment]
Hey @Tampa, thanks for the suggestion.
We would need to host the file somewhere since this is a static website. Where could we do it? I have not much experience with that.
Also, why is peertube.tv flagged as malicious? Maybe you have an idea @MagicLike 🤔

**Comment by tsterbak** [comment]
Virustotal thinks its fine
https://www.virustotal.com/gui/url/a4bb81a1d73ad6404b340dee614545b952a7a1ba14fefa017901db05e926e664/detection

**Comment by Tampa** [comment]
This is what I see when I navigate to https://openandroidinstaller.org/

![image](https://github.com/openandroidinstaller-dev/openandroidinstaller-dev.github.io/assets/1579370/107ddfbe-696f-48a5-a748-c4cb7e18cb44)


What stops you from putting it in github itself? Far as I know they only recommend keeping repos small, don't actually stop you from putting a 200mb videofile in there. As webm it should be relatively small. Alternatively could put just the videofiles into a separate repo and reference the raw file link.
